#include <gtest/gtest.h>
#include "core/generic_hardware/DebugStream.h"
#include "core/cli/BaseFlag.h"
#include "core/cli/SimpleFlag.h"
#include "core/cli/ArgumentFlag.h"

void callback(DebugStream*) {}

TEST(SimpleFlag, TestAccessors) {
    SimpleFlag testA("--testA", "some help text", true, callback);

    EXPECT_STREQ(testA.name(), "--testA");
    EXPECT_STREQ(testA.help(), "some help text");
    EXPECT_TRUE(testA.isRequired());
    EXPECT_FALSE(testA.isSet());
    EXPECT_FALSE(testA.verify());
}

TEST(SimpleFlag, TestParse) {
    SimpleFlag testA("--testA", "some help text", true, callback);

    ASSERT_EQ(testA.parse(nullptr), 0); // simple flags have no arguments to parse
    EXPECT_TRUE(testA.isSet());
    EXPECT_TRUE(testA.getValueDerived());
    EXPECT_TRUE(testA.verify());

    testA.reset();
    EXPECT_FALSE(testA.isSet());
    EXPECT_TRUE(testA.isRequired());
    EXPECT_STREQ(testA.name(), "--testA");
    EXPECT_STREQ(testA.help(), "some help text");
    EXPECT_FALSE(testA.getValueDerived());
}

TEST(ArgumentFlag, TestAccessors) {
    ArgumentFlag<int> testA("--testA", 5, "some help text", true, callback);
    EXPECT_STREQ(testA.name(), "--testA");
    EXPECT_STREQ(testA.help(), "some help text");
    EXPECT_TRUE(testA.isRequired());
    EXPECT_FALSE(testA.isSet());
    EXPECT_FALSE(testA.verify());

    // special case of const char* input
    ArgumentFlag<const char*> testB("--testB", "defaultTest", "some help text", false, callback);
    EXPECT_STREQ(testB.name(), "--testB");
    EXPECT_STREQ(testB.help(), "some help text");
    EXPECT_FALSE(testB.isRequired());
    EXPECT_FALSE(testB.isSet());
    EXPECT_TRUE(testB.verify());

    // no default value provided
    ArgumentFlag<double> testC("--testC", "some help text", true, callback);
    EXPECT_STREQ(testC.name(), "--testC");
    EXPECT_STREQ(testC.help(), "some help text");
    EXPECT_TRUE(testC.isRequired());
    EXPECT_FALSE(testC.isSet());
    EXPECT_FALSE(testC.verify());
}

TEST(ArgumentFlag, TestParse) {
    // forced to use default
    ArgumentFlag<int> testA("--testA", 0, "some help text", true, callback);

    ASSERT_EQ(testA.parse(nullptr), 0); // no argument, falls back to default
    EXPECT_TRUE(testA.isSet());
    EXPECT_EQ(testA.getValueDerived(), 0);
    EXPECT_TRUE(testA.verify());

    testA.reset();
    EXPECT_FALSE(testA.isSet());
    EXPECT_TRUE(testA.isRequired());

    ArgumentFlag<const char*> testB("--testB", "defaultTest", "some help text", true, callback);
    char argB[] = "changedText";

    ASSERT_EQ(testB.parse(argB), 0);
    EXPECT_TRUE(testB.isSet());
    EXPECT_STREQ(testB.getValueDerived(), "changedText");

    ArgumentFlag<double> testC("--testC", "some help text", true, callback);
    char argC[] = "5.1";

    ASSERT_EQ(testC.parse(argC), 0);
    EXPECT_TRUE(testC.isSet());
    EXPECT_EQ(testC.getValueDerived(), 5.1);
}

TEST(ArgumentFlag, TestFailure) {
    // no default value and no argument
    ArgumentFlag<int> testA("--testA", "some help text", true, callback);
    ASSERT_EQ(testA.parse(nullptr), CLI_NO_DEFAULT_VALUE_SET);

    // wrong type input
    ArgumentFlag<int> testB("--testB", 0, "some help text", true, callback);
    char argB[] = "abc";
    ASSERT_EQ(testB.parse(argB), CLI_PARSE_FAILED_TO_PARSE_ARGUMENT);

    // trailing garbage after a valid number
    ArgumentFlag<double> testC("--testC", 5.0, "some help text", true, callback);
    char argC[] = "123abc";
    ASSERT_EQ(testC.parse(argC), CLI_PARSE_FAILED_TO_PARSE_ARGUMENT);
}

TEST(SimpleFlag, TestRunPassesDebugStream) {
    DebugStream stream;
    DebugStream* received = nullptr;
    SimpleFlag testA("--testA", "some help text", true, [&received](DebugStream* debugStream) { received = debugStream; });

    testA.run(&stream);
    EXPECT_EQ(received, &stream);
}

TEST(ArgumentFlag, TestRunPassesDebugStream) {
    DebugStream stream;
    DebugStream* received = nullptr;
    ArgumentFlag<int> testA("--testA", 5, "some help text", true, [&received](DebugStream* debugStream) { received = debugStream; });

    testA.run(&stream);
    EXPECT_EQ(received, &stream);
}

TEST(SimpleFlag, TestHelpTextIsNotCopied) {
    // name()/help() must return the exact pointers passed in, not a copy - required for
    // autogenerated help text to work off static string literals with no internal buffering.
    const char* name = "--testA";
    const char* helpText = "some help text";
    SimpleFlag testA(name, helpText, true, callback);

    EXPECT_EQ(testA.name(), name);
    EXPECT_EQ(testA.help(), helpText);
}

TEST(ArgumentFlag, TestHelpTextIsNotCopied) {
    const char* name = "--testA";
    const char* helpText = "some help text";
    ArgumentFlag<int> testA(name, 5, helpText, true, callback);

    EXPECT_EQ(testA.name(), name);
    EXPECT_EQ(testA.help(), helpText);
}
