#include <gtest/gtest.h>
#include "core/generic_hardware/DebugStream.h"
#include "core/cli/Parser.h"
#include "core/cli/SimpleFlag.h"
#include "core/cli/ArgumentFlag.h"
#include "core/cli/ReturnCodes.h"

void callback(DebugStream*) {}

// Captures written bytes instead of sending them anywhere, so help-text tests can assert on it.
class CapturingDebugStream : public DebugStream {
public:
    std::string captured;

protected:
    size_t write(const void* buffer, size_t size) override {
        captured.append(static_cast<const char*>(buffer), size);
        return size;
    }
};

TEST(ParserTest, TestBasic) {
    // basic parsing with a SimpleFlag
    Parser testParserA = Parser();
    SimpleFlag testA("--testA", "some help text", true, callback);
    BaseFlag* testAGroup[] = {&testA};
    testParserA.addFlagGroup(testAGroup);

    EXPECT_FALSE(testA.isSet());
    char argsA[] = "--testA";
    ASSERT_EQ(testParserA.parse(argsA), 0);
    EXPECT_TRUE(testA.isSet());

    // basic parsing with an ArgumentFlag
    Parser testParserB = Parser();
    ArgumentFlag<int> testB("--testB", 5, "some help text", true, callback);
    BaseFlag* testBGroup[] = {&testB};
    testParserB.addFlagGroup(testBGroup);

    EXPECT_FALSE(testB.isSet());
    char argsB[] = "--testB";
    ASSERT_EQ(testParserB.parse(argsB), 0);
    EXPECT_TRUE(testB.isSet());
    EXPECT_EQ(testB.getValueDerived(), 5);
}

TEST(ParserTest, TestMultiple) {
    // parsing with multiple SimpleFlags
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "some help text", true, callback);
    SimpleFlag testA_2("-a", "help", true, callback);
    SimpleFlag testA_3("-b", "help", false, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2, &testA_3};
    testParserA.addFlagGroup(testGroupA);

    char argsA[] = "--testA -a -b";
    ASSERT_EQ(testParserA.parse(argsA), CLI_SUCCESS);
    EXPECT_TRUE(testA_1.isSet());
    EXPECT_TRUE(testA_2.isSet());
    EXPECT_TRUE(testA_3.isSet());

    // parsing with multiple ArgumentFlags
    Parser testParserB = Parser();
    ArgumentFlag<int> testB_1("--testB", "some help text", true, callback);
    ArgumentFlag<int> testB_2("-a", 0, "some help text", false, callback);
    ArgumentFlag<double> testB_3("-b", "some help text", true, callback);
    BaseFlag* testGroupB[] = {&testB_1, &testB_2, &testB_3};
    testParserB.addFlagGroup(testGroupB);

    char argsB[] = "--testB 5 -a -b -5.2";
    ASSERT_EQ(testParserB.parse(argsB), 0);
}

TEST(ParserTest, TestComplex) {
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "some help text", true, callback);
    ArgumentFlag<int> testA_2("-a", "help", true, callback);
    ArgumentFlag<const char*> testA_3("-b", "help", true, callback);
    SimpleFlag testA_4("-c", "help", true, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2, &testA_3, &testA_4};
    testParserA.addFlagGroup(testGroupA);

    char argsA[] = "--testA -a 5 -b \"hello world\" -c";
    ASSERT_EQ(testParserA.parse(argsA), 0);

    const char* outputA_3;
    EXPECT_EQ(testParserA.getValue<const char*>("--testA", "-b", outputA_3), 0);
    EXPECT_STREQ(testA_3.getValueDerived(), outputA_3);
    EXPECT_STREQ(outputA_3, "hello world");
}

TEST(ParserTest, TestHelp) {
    // help text is autogenerated from each flag's name/required/help - not hand-written
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "some help for --testA", true, callback);
    ArgumentFlag<int> testA_2("-a", 0, "provide an integer", false, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2};
    testParserA.addFlagGroup(testGroupA);

    CapturingDebugStream stream;
    testParserA.printHelp(&stream);
    std::string expectedA = "--testA [Required]: some help for --testA\n"
                            "    -a [Optional]: provide an integer\n\n";
    EXPECT_EQ(stream.captured, expectedA);
}

TEST(ParserTest, TestHelpReflectsRegisteredFlags) {
    // changing which flags are registered changes the printed text - it isn't a fixed blob
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "leader help", true, callback);
    ArgumentFlag<int> testA_2("-x", 0, "an extra flag", false, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2};
    testParserA.addFlagGroup(testGroupA);

    CapturingDebugStream stream;
    testParserA.printHelp(&stream);
    EXPECT_NE(stream.captured.find("    -x [Optional]: an extra flag"), std::string::npos);
    EXPECT_EQ(stream.captured.find("-y"), std::string::npos);
}

TEST(ParserTest, TestHelpOmitsEmptyHelpText) {
    // a flag with no help text shouldn't print a dangling separator after it
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "leader help", true, callback);
    SimpleFlag testA_2("-set", "", false, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2};
    testParserA.addFlagGroup(testGroupA);

    CapturingDebugStream stream;
    testParserA.printHelp(&stream);
    EXPECT_NE(stream.captured.find("    -set [Optional]\n"), std::string::npos);
}

TEST(ParserTest, TestHelpFlagEndToEnd) {
    // a --help flag wired to printHelp() should report every flag in its own group when triggered
    Parser testParserA = Parser();
    CapturingDebugStream stream;
    SimpleFlag testA_1("--testA", "leader help", true, callback);
    ArgumentFlag<int> testA_2("-a", 0, "provide an integer", false, callback);
    SimpleFlag helpFlag("--help", "Prints this help text", false, [&testParserA](DebugStream* debugStream) { testParserA.printHelp(debugStream); });
    BaseFlag* testGroupA[] = {&testA_1, &testA_2, &helpFlag};
    testParserA.addFlagGroup(testGroupA);

    char argsA[] = "--testA --help";
    ASSERT_EQ(testParserA.parse(argsA), 0);
    ASSERT_EQ(testParserA.runFlags(&stream), CLI_SUCCESS);
    EXPECT_NE(stream.captured.find("--testA [Required]: leader help"), std::string::npos);
    EXPECT_NE(stream.captured.find("    -a [Optional]: provide an integer"), std::string::npos);
}

TEST(ParserTest, TestReset) {
    // test that reset unsets a flag
    Parser testParserA = Parser();
    SimpleFlag testA_1("--testA", "some help for --testA", true, callback);
    ArgumentFlag<int> testA_2("-a", 0, "provide an integer", false, callback);
    BaseFlag* testGroupA[] = {&testA_1, &testA_2};
    testParserA.addFlagGroup(testGroupA);

    char argsA[] = "--testA -a 5";
    ASSERT_EQ(testParserA.parse(argsA), 0);
    EXPECT_TRUE(testA_1.isSet());
    EXPECT_TRUE(testA_2.isSet());

    testParserA.resetFlags();
    EXPECT_FALSE(testA_1.isSet());
    EXPECT_FALSE(testA_2.isSet());
}

TEST(ParserTest, TestFailure1) {
    // providing no FlagGroup to parse
    Parser testParserA = Parser();
    char argsA[] = "";
    ASSERT_EQ(testParserA.parse(argsA), CLI_PARSER_NO_FLAG_GROUP_PROVIDED);

    // providing no flags to parse
    Parser testParserB = Parser();
    ArgumentFlag<int> testB_1("--testB", "some help text", true, callback);
    BaseFlag* testGroupB[] = {&testB_1};
    testParserB.addFlagGroup(testGroupB);

    char argsB[] = "";
    ASSERT_EQ(testParserB.parse(argsB), CLI_PARSER_NO_FLAGS_PROVIDED);
}

TEST(ParserTest, TestFailure2) {
    // adding flag group, but wrong first flag provided
    Parser testParserC = Parser();
    ArgumentFlag<int> testC_1("--testC", "some help text", true, callback);
    ArgumentFlag<int> testC_2("-a", "some help text", true, callback);
    BaseFlag* testGroupC[] = {&testC_1, &testC_2};
    testParserC.addFlagGroup(testGroupC);

    char argsC[] = "--flag_group";
    ASSERT_EQ(testParserC.parse(argsC), CLI_PARSER_NO_LEADER_FLAG);

    // parsing an unknown flag
    Parser testParserD = Parser();
    ArgumentFlag<int> testD_1("--testD", "some help text", true, callback);
    ArgumentFlag<int> testD_2("-a", "some help text", true, callback);
    BaseFlag* testGroupD[] = {&testD_1, &testD_2};
    testParserD.addFlagGroup(testGroupD);

    char argsD[] = "--testD 5 -b 2";
    ASSERT_EQ(testParserD.parse(argsD), CLI_PARSER_UNKNOWN_FLAG);
}

TEST(ParserTest, TestFailure3) {
    // when missing a required argument
    Parser testParserE = Parser();
    SimpleFlag testE_1("--testE", "some help text", true, callback);
    ArgumentFlag<int> testE_2("-a", "some help text", true, callback);
    BaseFlag* testGroupE[] = {&testE_1, &testE_2};
    testParserE.addFlagGroup(testGroupE);

    char argsE[] = "--testE";
    ASSERT_EQ(testParserE.parse(argsE), CLI_PARSER_MISSING_REQUIRED_ARGS);
}

TEST(ParserTest, TestRunFlagsPassesDebugStream) {
    // runFlags() should forward its DebugStream* through to the triggered flag's callback
    Parser testParserA = Parser();
    DebugStream stream;
    DebugStream* received = nullptr;
    SimpleFlag testA("--testA", "some help text", true, [&received](DebugStream* debugStream) { received = debugStream; });
    BaseFlag* testAGroup[] = {&testA};
    testParserA.addFlagGroup(testAGroup);

    char argsA[] = "--testA";
    ASSERT_EQ(testParserA.parse(argsA), 0);
    ASSERT_EQ(testParserA.runFlags(&stream), CLI_SUCCESS);
    EXPECT_EQ(received, &stream);
}

TEST(ParserTest, TestRunFlagsSkipsUnsetFlags) {
    // only flags that were actually set on the most recent parse should run
    Parser testParserA = Parser();
    DebugStream stream;
    bool aRan = false, bRan = false;
    SimpleFlag testA_1("--testA", "some help text", true, [&aRan](DebugStream*) { aRan = true; });
    SimpleFlag testA_2("-a", "help", false, [&bRan](DebugStream*) { bRan = true; });
    BaseFlag* testGroupA[] = {&testA_1, &testA_2};
    testParserA.addFlagGroup(testGroupA);

    char argsA[] = "--testA";
    ASSERT_EQ(testParserA.parse(argsA), 0);
    ASSERT_EQ(testParserA.runFlags(&stream), CLI_SUCCESS);
    EXPECT_TRUE(aRan);
    EXPECT_FALSE(bRan);
}
