#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H

#include <Avionics.h>

// SillyGooseV1 Hardware
#if IS_BOARD_VERSION(1)
#define SENSE_R1 10.0f
#define SENSE_R2 10.0f
#define SILLY_GOOSE_NAME "SillyGooseV1"
// SillyGooseV2 Hardware
#elif IS_BOARD_VERSION(2)
#define SENSE_R1 30.0f
#define SENSE_R2 10.0f
#define SILLY_GOOSE_NAME "SillyGooseV2"
#endif

#define FRAM_CS_PIN (13)
#define FLASH_CS_PIN (12)
#define FRAM_HOLD_PIN (10)
#define FLASH_HOLD_PIN (11)
#define IMU_INT_PIN (6)
#define STATUS_PIN (A5)
#define BOOT_PIN (5)

#define BUZZER_PIN (0)
#define LIGHT_PIN (1)

#define VOLTAGE_SENSE_PIN (A4)
#define VOLTAGE_SENSE_SCALE (((SENSE_R1 + SENSE_R2) / SENSE_R2) * (3.3f / 1023.0f))

#define PYRO1_GATE_PIN (9)
#define PYRO1_SENSE_PIN (A2)
#define PYRO2_GATE_PIN (A3)
#define PYRO2_SENSE_PIN (A1)
#define PYRO_SENSE_THRESHOLD (200)

#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H
