#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H

#define FRAM_CS_PIN (13)
#define FLASH_CS_PIN (12)
#define FRAM_HOLD_PIN (10)
#define FLASH_HOLD_PIN (11)
#define IMU_INT_PIN (6)

#define BUZZER_PIN (0)
#define LIGHT_PIN (1)

#define VOLTAGE_SENSE_PIN (A4)
#define VOLTAGE_SENSE_SCALE (2.0 * (3.3 / 1023.0))

#define PYRO1_GATE_PIN (9)
#define PYRO1_SENSE_PIN (A2)
#define PYRO2_GATE_PIN (A3)
#define PYRO2_SENSE_PIN (A1)
#define PYRO_SENSE_THRESHOLD (200)

#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_SILLYGOOSEPINS_H