#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_CONFIGURATIONREGISTRY_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_CONFIGURATIONREGISTRY_H

// Place any structs used by the config below

// Register all config variables
// Syntax: DEFINE_CONFIGURATION_VARIABLE(NAME, type_t, defaultValue)
// clang-format off
DEFINE_CONFIGURATION_VARIABLE(FLIGHT_STATE, int32_t, UNKNOWN_FLIGHT_STATE)
DEFINE_CONFIGURATION_VARIABLE(GROUND_ELEVATION, float, 0.0)
DEFINE_CONFIGURATION_VARIABLE(GROUND_TEMPERATURE, float, 273.15)
DEFINE_CONFIGURATION_VARIABLE(RADIO_FREQUENCY, float, 915.0)
DEFINE_CONFIGURATION_VARIABLE(MAIN_ELEVATION, float, 200.0)
DEFINE_CONFIGURATION_VARIABLE(DROGUE_DELAY, uint32_t, 1000)
DEFINE_CONFIGURATION_VARIABLE(BATTERY_VOLTAGE_SENSOR_SCALE_FACTOR, float, 1.0)
// clang-format on

#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_CONFIGURATIONREGISTRY_H
