#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_DETECTOR_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_DETECTOR_H

class Detector {
public:


protected:
    
};

#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_DETECTOR_H
