#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_LSM6DSV320XSENSOR_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_LSM6DSV320XSENSOR_H

#include <Avionics.h>
#include "../../core/generic_hardware/GenericSensor.h"


class LSM6DSV320XSensor final : public GenericSensor {

};



#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_LSM6DSV320XSENSOR_H