//
// Created by chris on 7/23/2025.
//

#ifndef PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_RETURNCODES_H
#define PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_RETURNCODES_H

enum CLIReturnCode_e {
    CLI_SUCCESS = 0,
    CLI_NO_DEFAULT_VALUE_SET = -1,
    CLI_PARSE_FAILED_TO_PARSE_ARGUMENT = -2,
    CLI_PARSE_FAIL_EXTRA_ARGUMENTS = -3,
    CLI_PARSER_NO_FLAG_GROUP_PROVIDED = -4,
    CLI_PARSER_NO_FLAGS_PROVIDED = -5,
    CLI_PARSER_UNKNOWN_FLAG = -6,
    CLI_PARSER_NO_LEADER_FLAG = -7,
    CLI_PARSER_MISSING_REQUIRED_ARGS = -8,
    CLI_PARSER_UNKNOWN_FLAG_GROUP = -9,
    CLI_PARSER_MISSING_LATEST_FLAG_GROUP = -10,
    CLI_PARSER_ZERO_FLAG_GROUPS_ADDED = -11,
    CLI_PARSER_MAXIMUM_FLAG_GROUPS_EXCEEDED = -12,
    CLI_PARSER_FLAG_NOT_FOUND = -14,
    CLI_PARSER_FLAG_GROUP_NOT_FOUND = -13,
};

#endif //PLATFORMIO_NULI_AVIONICS_FLIGHT_SOFTWARE_RETURNCODES_H
